Allow customizing the Application Context builder
micronaut-projects/micronaut-azure pull request #393
Opened 2022-11-09 18:22 UTC by BenD10

Fixes #392

Allows us to customize the application context, specifically in our case so we can eagerly initialise singletons on our premium Azure function.

2022-11-09 18:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-azure?pullRequest=393) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-azure?pullRequest=393) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-azure?pullRequest=393) it.</sub>

2022-11-17 11:27 UTC, graemerocher commented
PR doesn't compile

2022-11-17 14:22 UTC, BenD10 commented
My apologises @graemerocher, it should be fixed now.

2022-11-18 15:00 UTC, graemerocher requested changes

2022-11-18 15:00 UTC, graemerocher commented on azure-function/src/main/java/io/micronaut/azure/function/AzureFunction.java
> +    protected static ApplicationContextBuilder newApplicationContextBuilder() {
method needs javadoc and please annotate the return type with `@NonNull`

2022-11-19 09:05 UTC, merged

2022-11-19 09:05 UTC, graemerocher commented
Thanks!